# Generated by Django 5.0.7 on 2024-08-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkgeneration',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='networkgeneration',
            name='name',
            field=models.CharField(default='Default name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitegsm',
            name='location',
            field=models.CharField(default='default location', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitegsm',
            name='name',
            field=models.CharField(default='default name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitegsm',
            name='network_generation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
